"""initial_clinical_schema

Revision ID: 27ef246b3e8d
Revises: 
Create Date: 2026-08-15 18:03:46.994170
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27ef246b3e8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_case_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('patient_reference', sa.String(length=256), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_sex', sa.String(length=32), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('case_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_case_external_case_id'), 'clinical_case', ['external_case_id'], unique=False)
    op.create_index(op.f('ix_clinical_case_status'), 'clinical_case', ['status'], unique=False)
    op.create_table('clinical_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('processed_row_count', sa.Integer(), nullable=False),
    sa.Column('error_row_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('import_metadata', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_case.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_import_case_id'), 'clinical_import', ['case_id'], unique=False)
    op.create_index(op.f('ix_clinical_import_checksum'), 'clinical_import', ['checksum'], unique=False)
    op.create_index(op.f('ix_clinical_import_status'), 'clinical_import', ['status'], unique=False)
    op.create_table('clinical_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('encounter_reference', sa.String(length=128), nullable=True),
    sa.Column('encounter_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_reference', sa.String(length=256), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('pregnancy_status', sa.String(length=32), nullable=True),
    sa.Column('smoking_status', sa.String(length=32), nullable=True),
    sa.Column('alcohol_use', sa.String(length=32), nullable=True),
    sa.Column('vital_signs', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('current_medications', sa.JSON(), nullable=False),
    sa.Column('medical_history', sa.JSON(), nullable=False),
    sa.Column('surgical_history', sa.JSON(), nullable=False),
    sa.Column('family_history', sa.JSON(), nullable=False),
    sa.Column('social_history', sa.JSON(), nullable=False),
    sa.Column('additional_metadata', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_clinical_metadata_case_id')
    )
    op.create_index(op.f('ix_clinical_metadata_case_id'), 'clinical_metadata', ['case_id'], unique=False)
    op.create_table('clinical_import_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('record_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_case.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['clinical_import.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'record_number', name='uq_clinical_import_record_number')
    )
    op.create_index(op.f('ix_clinical_import_record_case_id'), 'clinical_import_record', ['case_id'], unique=False)
    op.create_index(op.f('ix_clinical_import_record_import_id'), 'clinical_import_record', ['import_id'], unique=False)
    op.create_index(op.f('ix_clinical_import_record_status'), 'clinical_import_record', ['status'], unique=False)
    op.create_table('processing_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('execution_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('output_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_case.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['clinical_import.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_execution_case_id'), 'processing_execution', ['case_id'], unique=False)
    op.create_index(op.f('ix_processing_execution_import_id'), 'processing_execution', ['import_id'], unique=False)
    op.create_index(op.f('ix_processing_execution_status'), 'processing_execution', ['status'], unique=False)
    op.create_table('diagnostic_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('diagnosis_code', sa.String(length=64), nullable=True),
    sa.Column('diagnosis_label', sa.String(length=256), nullable=False),
    sa.Column('clinical_narrative', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['processing_execution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_result_case_id'), 'diagnostic_result', ['case_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_result_execution_id'), 'diagnostic_result', ['execution_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_result_result_status'), 'diagnostic_result', ['result_status'], unique=False)
    op.create_index(op.f('ix_diagnostic_result_risk_level'), 'diagnostic_result', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_result_risk_level'), table_name='diagnostic_result')
    op.drop_index(op.f('ix_diagnostic_result_result_status'), table_name='diagnostic_result')
    op.drop_index(op.f('ix_diagnostic_result_execution_id'), table_name='diagnostic_result')
    op.drop_index(op.f('ix_diagnostic_result_case_id'), table_name='diagnostic_result')
    op.drop_table('diagnostic_result')
    op.drop_index(op.f('ix_processing_execution_status'), table_name='processing_execution')
    op.drop_index(op.f('ix_processing_execution_import_id'), table_name='processing_execution')
    op.drop_index(op.f('ix_processing_execution_case_id'), table_name='processing_execution')
    op.drop_table('processing_execution')
    op.drop_index(op.f('ix_clinical_import_record_status'), table_name='clinical_import_record')
    op.drop_index(op.f('ix_clinical_import_record_import_id'), table_name='clinical_import_record')
    op.drop_index(op.f('ix_clinical_import_record_case_id'), table_name='clinical_import_record')
    op.drop_table('clinical_import_record')
    op.drop_index(op.f('ix_clinical_metadata_case_id'), table_name='clinical_metadata')
    op.drop_table('clinical_metadata')
    op.drop_index(op.f('ix_clinical_import_status'), table_name='clinical_import')
    op.drop_index(op.f('ix_clinical_import_checksum'), table_name='clinical_import')
    op.drop_index(op.f('ix_clinical_import_case_id'), table_name='clinical_import')
    op.drop_table('clinical_import')
    op.drop_index(op.f('ix_clinical_case_status'), table_name='clinical_case')
    op.drop_index(op.f('ix_clinical_case_external_case_id'), table_name='clinical_case')
    op.drop_table('clinical_case')
    # ### end Alembic commands ###
